### ISSUE TITLE
ObjectiveCLab - TODO

### ISSUE THREAD

**Issue by youbinoyou** [TeamSunstripe/ObjectiveCLab#15]
**関連管理**
https://github.com/youbinoyou/KaraageChannel/issues/10

**画面一覧**

#56 

**機能一覧**

#55 

**参考サイト**
- [x] http://secondflush2.blog.fc2.com/blog-entry-48.html
- [ ] [[Xcode][warning]まとめ](http://qiita.com/sunstripe/items/af298e03286732343439)

機能
---

ユーザー登録して、ObjectiveCLabをもっと便利に使ってみませんか。
あなたにマッチした記事/アプリをお届けします！！
ユーザーやタグをフォローすることで、あなたが興味を持つ技術分野の情報をまとめてキャッチアップできます。
便利な情報をあとで効率的に読み返せます。
気に入った記事を「ストック」することで、あとからすぐに検索できます。

より詳しく 

|ボタン名|ボタン名|
|:--:|:--:|
|登録する|ログインする|

こども向けの学習
- [x] https://studio.beatnix.co.jp/develop/swift/ios-custom-button/

エンジニア向けの学習
開発者現場向けの学習
シニア向けの学習

トップの整理
ニュースがあってもいいかな？
- [ ] https://dev.classmethod.jp/smartphone/deprecated-openurl/
